#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
Name     : xscreensaver
Version  : 6.08
Release  : 36
URL      : https://www.jwz.org/xscreensaver/xscreensaver-6.08.tar.gz
Source0  : https://www.jwz.org/xscreensaver/xscreensaver-6.08.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: xscreensaver-bin = %{version}-%{release}
Requires: xscreensaver-data = %{version}-%{release}
Requires: xscreensaver-libexec = %{version}-%{release}
Requires: xscreensaver-locales = %{version}-%{release}
Requires: xscreensaver-man = %{version}-%{release}
Requires: xorg-fonts
BuildRequires : Linux-PAM-dev
BuildRequires : bc
BuildRequires : buildreq-configure
BuildRequires : gdk-pixbuf-dev
BuildRequires : gdk-pixbuf-xlib-dev
BuildRequires : gettext
BuildRequires : glibc-staticdev
BuildRequires : glu-dev
BuildRequires : gtk+-dev
BuildRequires : intltool
BuildRequires : intltool-dev
BuildRequires : krb5-dev
BuildRequires : libXext-dev
BuildRequires : libXinerama-dev
BuildRequires : libXmu-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : lightdm
BuildRequires : perl
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gdk-pixbuf-2.0)
BuildRequires : pkgconfig(gl)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(systemd)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xi)
BuildRequires : pkgconfig(xpm)
BuildRequires : pkgconfig(xrandr)
BuildRequires : xorg-fonts
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Do-not-warn-about-invalid-PAM-directories.patch
Patch2: build.patch

%description
A modular screen saver and locker for the X Window System.
More than 250 display modes are included in this package.

%package bin
Summary: bin components for the xscreensaver package.
Group: Binaries
Requires: xscreensaver-data = %{version}-%{release}
Requires: xscreensaver-libexec = %{version}-%{release}

%description bin
bin components for the xscreensaver package.


%package data
Summary: data components for the xscreensaver package.
Group: Data

%description data
data components for the xscreensaver package.


%package extras
Summary: extras components for the xscreensaver package.
Group: Default

%description extras
extras components for the xscreensaver package.


%package libexec
Summary: libexec components for the xscreensaver package.
Group: Default

%description libexec
libexec components for the xscreensaver package.


%package locales
Summary: locales components for the xscreensaver package.
Group: Default

%description locales
locales components for the xscreensaver package.


%package man
Summary: man components for the xscreensaver package.
Group: Default

%description man
man components for the xscreensaver package.


%prep
%setup -q -n xscreensaver-6.08
cd %{_builddir}/xscreensaver-6.08
%patch -P 1 -p1
%patch -P 2 -p1
pushd ..
cp -a xscreensaver-6.08 buildavx2
popd

%build
## build_prepend content
# otherwise autoreconf fails...
cp /usr/share/gettext/config.rpath .
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1697039905
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%reconfigure --disable-static --with-xpm \
--with-pam \
--with-dpms-ext
make  %{?_smp_mflags}  all
unset PKG_CONFIG_PATH
pushd ../buildavx2/
## build_prepend content
# otherwise autoreconf fails...
cp /usr/share/gettext/config.rpath .
## build_prepend end
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -m64 -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -m64 -march=x86-64-v3 "
%reconfigure --disable-static --with-xpm \
--with-pam \
--with-dpms-ext
make  %{?_smp_mflags}  all
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1697039905
rm -rf %{buildroot}
pushd ../buildavx2/
%make_install_v3
popd
%make_install
%find_lang xscreensaver
## install_append content
# Makefile.in is just too ancient to reconf, checks for /etc/pam.d existence
install -m 00644 -D driver/xscreensaver.pam $RPM_BUILD_ROOT/usr/share/pam.d/xscreensaver
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib/X11/app-defaults/XScreenSaver

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/xscreensaver
/V3/usr/bin/xscreensaver-command
/V3/usr/bin/xscreensaver-settings
/usr/bin/xscreensaver
/usr/bin/xscreensaver-command
/usr/bin/xscreensaver-demo
/usr/bin/xscreensaver-settings

%files data
%defattr(-,root,root,-)
/usr/share/applications/xscreensaver-settings.desktop
/usr/share/applications/xscreensaver.desktop
/usr/share/fonts/xscreensaver/OCRA.ttf
/usr/share/fonts/xscreensaver/SpecialElite.ttf
/usr/share/fonts/xscreensaver/clacon.ttf
/usr/share/fonts/xscreensaver/gallant12x22.ttf
/usr/share/fonts/xscreensaver/luximr.ttf
/usr/share/pam.d/xscreensaver
/usr/share/pixmaps/xscreensaver.png
/usr/share/xscreensaver/config/README
/usr/share/xscreensaver/config/cubocteversion.xml
/usr/share/xscreensaver/config/droste.xml
/usr/share/xscreensaver/config/hextrail.xml
/usr/share/xscreensaver/config/papercube.xml
/usr/share/xscreensaver/config/skulloop.xml
/usr/share/xscreensaver/xscreensaver.service

%files extras
%defattr(-,root,root,-)
/V3/usr/libexec/xscreensaver/abstractile
/V3/usr/libexec/xscreensaver/anemone
/V3/usr/libexec/xscreensaver/anemotaxis
/V3/usr/libexec/xscreensaver/antinspect
/V3/usr/libexec/xscreensaver/antmaze
/V3/usr/libexec/xscreensaver/antspotlight
/V3/usr/libexec/xscreensaver/apollonian
/V3/usr/libexec/xscreensaver/apple2
/V3/usr/libexec/xscreensaver/atlantis
/V3/usr/libexec/xscreensaver/attraction
/V3/usr/libexec/xscreensaver/atunnel
/V3/usr/libexec/xscreensaver/barcode
/V3/usr/libexec/xscreensaver/beats
/V3/usr/libexec/xscreensaver/binaryhorizon
/V3/usr/libexec/xscreensaver/binaryring
/V3/usr/libexec/xscreensaver/blaster
/V3/usr/libexec/xscreensaver/blinkbox
/V3/usr/libexec/xscreensaver/blitspin
/V3/usr/libexec/xscreensaver/blocktube
/V3/usr/libexec/xscreensaver/boing
/V3/usr/libexec/xscreensaver/bouboule
/V3/usr/libexec/xscreensaver/bouncingcow
/V3/usr/libexec/xscreensaver/boxed
/V3/usr/libexec/xscreensaver/boxfit
/V3/usr/libexec/xscreensaver/braid
/V3/usr/libexec/xscreensaver/bsod
/V3/usr/libexec/xscreensaver/bubble3d
/V3/usr/libexec/xscreensaver/bumps
/V3/usr/libexec/xscreensaver/cage
/V3/usr/libexec/xscreensaver/carousel
/V3/usr/libexec/xscreensaver/ccurve
/V3/usr/libexec/xscreensaver/celtic
/V3/usr/libexec/xscreensaver/chompytower
/V3/usr/libexec/xscreensaver/circuit
/V3/usr/libexec/xscreensaver/cityflow
/V3/usr/libexec/xscreensaver/cloudlife
/V3/usr/libexec/xscreensaver/companioncube
/V3/usr/libexec/xscreensaver/compass
/V3/usr/libexec/xscreensaver/coral
/V3/usr/libexec/xscreensaver/covid19
/V3/usr/libexec/xscreensaver/crackberg
/V3/usr/libexec/xscreensaver/crumbler
/V3/usr/libexec/xscreensaver/crystal
/V3/usr/libexec/xscreensaver/cube21
/V3/usr/libexec/xscreensaver/cubenetic
/V3/usr/libexec/xscreensaver/cubestack
/V3/usr/libexec/xscreensaver/cubestorm
/V3/usr/libexec/xscreensaver/cubetwist
/V3/usr/libexec/xscreensaver/cubicgrid
/V3/usr/libexec/xscreensaver/cwaves
/V3/usr/libexec/xscreensaver/cynosure
/V3/usr/libexec/xscreensaver/dangerball
/V3/usr/libexec/xscreensaver/decayscreen
/V3/usr/libexec/xscreensaver/deco
/V3/usr/libexec/xscreensaver/deepstars
/V3/usr/libexec/xscreensaver/deluxe
/V3/usr/libexec/xscreensaver/demon
/V3/usr/libexec/xscreensaver/discoball
/V3/usr/libexec/xscreensaver/discrete
/V3/usr/libexec/xscreensaver/distort
/V3/usr/libexec/xscreensaver/drift
/V3/usr/libexec/xscreensaver/dymaxionmap
/V3/usr/libexec/xscreensaver/endgame
/V3/usr/libexec/xscreensaver/energystream
/V3/usr/libexec/xscreensaver/engine
/V3/usr/libexec/xscreensaver/epicycle
/V3/usr/libexec/xscreensaver/eruption
/V3/usr/libexec/xscreensaver/esper
/V3/usr/libexec/xscreensaver/etruscanvenus
/V3/usr/libexec/xscreensaver/euler2d
/V3/usr/libexec/xscreensaver/fadeplot
/V3/usr/libexec/xscreensaver/fiberlamp
/V3/usr/libexec/xscreensaver/filmleader
/V3/usr/libexec/xscreensaver/fireworkx
/V3/usr/libexec/xscreensaver/flame
/V3/usr/libexec/xscreensaver/flipflop
/V3/usr/libexec/xscreensaver/flipscreen3d
/V3/usr/libexec/xscreensaver/fliptext
/V3/usr/libexec/xscreensaver/flow
/V3/usr/libexec/xscreensaver/fluidballs
/V3/usr/libexec/xscreensaver/flurry
/V3/usr/libexec/xscreensaver/flyingtoasters
/V3/usr/libexec/xscreensaver/fontglide
/V3/usr/libexec/xscreensaver/fuzzyflakes
/V3/usr/libexec/xscreensaver/galaxy
/V3/usr/libexec/xscreensaver/gears
/V3/usr/libexec/xscreensaver/geodesic
/V3/usr/libexec/xscreensaver/geodesicgears
/V3/usr/libexec/xscreensaver/gflux
/V3/usr/libexec/xscreensaver/gibson
/V3/usr/libexec/xscreensaver/glblur
/V3/usr/libexec/xscreensaver/glcells
/V3/usr/libexec/xscreensaver/gleidescope
/V3/usr/libexec/xscreensaver/glhanoi
/V3/usr/libexec/xscreensaver/glitchpeg
/V3/usr/libexec/xscreensaver/glknots
/V3/usr/libexec/xscreensaver/glmatrix
/V3/usr/libexec/xscreensaver/glplanet
/V3/usr/libexec/xscreensaver/glschool
/V3/usr/libexec/xscreensaver/glslideshow
/V3/usr/libexec/xscreensaver/glsnake
/V3/usr/libexec/xscreensaver/gltext
/V3/usr/libexec/xscreensaver/goop
/V3/usr/libexec/xscreensaver/grav
/V3/usr/libexec/xscreensaver/gravitywell
/V3/usr/libexec/xscreensaver/greynetic
/V3/usr/libexec/xscreensaver/halftone
/V3/usr/libexec/xscreensaver/halo
/V3/usr/libexec/xscreensaver/handsy
/V3/usr/libexec/xscreensaver/headroom
/V3/usr/libexec/xscreensaver/helix
/V3/usr/libexec/xscreensaver/hexadrop
/V3/usr/libexec/xscreensaver/hexstrut
/V3/usr/libexec/xscreensaver/hilbert
/V3/usr/libexec/xscreensaver/hopalong
/V3/usr/libexec/xscreensaver/hydrostat
/V3/usr/libexec/xscreensaver/hypertorus
/V3/usr/libexec/xscreensaver/hypnowheel
/V3/usr/libexec/xscreensaver/ifs
/V3/usr/libexec/xscreensaver/imsmap
/V3/usr/libexec/xscreensaver/interaggregate
/V3/usr/libexec/xscreensaver/interference
/V3/usr/libexec/xscreensaver/intermomentary
/V3/usr/libexec/xscreensaver/jigglypuff
/V3/usr/libexec/xscreensaver/jigsaw
/V3/usr/libexec/xscreensaver/juggler3d
/V3/usr/libexec/xscreensaver/julia
/V3/usr/libexec/xscreensaver/kaleidescope
/V3/usr/libexec/xscreensaver/kaleidocycle
/V3/usr/libexec/xscreensaver/klein
/V3/usr/libexec/xscreensaver/kumppa
/V3/usr/libexec/xscreensaver/lament
/V3/usr/libexec/xscreensaver/lavalite
/V3/usr/libexec/xscreensaver/lcdscrub
/V3/usr/libexec/xscreensaver/lockward
/V3/usr/libexec/xscreensaver/loop
/V3/usr/libexec/xscreensaver/m6502
/V3/usr/libexec/xscreensaver/mapscroller
/V3/usr/libexec/xscreensaver/marbling
/V3/usr/libexec/xscreensaver/maze
/V3/usr/libexec/xscreensaver/maze3d
/V3/usr/libexec/xscreensaver/memscroller
/V3/usr/libexec/xscreensaver/menger
/V3/usr/libexec/xscreensaver/metaballs
/V3/usr/libexec/xscreensaver/mirrorblob
/V3/usr/libexec/xscreensaver/moebius
/V3/usr/libexec/xscreensaver/moebiusgears
/V3/usr/libexec/xscreensaver/moire
/V3/usr/libexec/xscreensaver/moire2
/V3/usr/libexec/xscreensaver/molecule
/V3/usr/libexec/xscreensaver/morph3d
/V3/usr/libexec/xscreensaver/mountain
/V3/usr/libexec/xscreensaver/munch
/V3/usr/libexec/xscreensaver/nakagin
/V3/usr/libexec/xscreensaver/nerverot
/V3/usr/libexec/xscreensaver/noof
/V3/usr/libexec/xscreensaver/noseguy
/V3/usr/libexec/xscreensaver/pacman
/V3/usr/libexec/xscreensaver/pedal
/V3/usr/libexec/xscreensaver/peepers
/V3/usr/libexec/xscreensaver/penetrate
/V3/usr/libexec/xscreensaver/penrose
/V3/usr/libexec/xscreensaver/petri
/V3/usr/libexec/xscreensaver/phosphor
/V3/usr/libexec/xscreensaver/photopile
/V3/usr/libexec/xscreensaver/piecewise
/V3/usr/libexec/xscreensaver/pinion
/V3/usr/libexec/xscreensaver/pipes
/V3/usr/libexec/xscreensaver/polyhedra
/V3/usr/libexec/xscreensaver/polyominoes
/V3/usr/libexec/xscreensaver/polytopes
/V3/usr/libexec/xscreensaver/pong
/V3/usr/libexec/xscreensaver/popsquares
/V3/usr/libexec/xscreensaver/projectiveplane
/V3/usr/libexec/xscreensaver/providence
/V3/usr/libexec/xscreensaver/pulsar
/V3/usr/libexec/xscreensaver/pyro
/V3/usr/libexec/xscreensaver/qix
/V3/usr/libexec/xscreensaver/quasicrystal
/V3/usr/libexec/xscreensaver/queens
/V3/usr/libexec/xscreensaver/raverhoop
/V3/usr/libexec/xscreensaver/razzledazzle
/V3/usr/libexec/xscreensaver/rdbomb
/V3/usr/libexec/xscreensaver/ripples
/V3/usr/libexec/xscreensaver/rocks
/V3/usr/libexec/xscreensaver/romanboy
/V3/usr/libexec/xscreensaver/rorschach
/V3/usr/libexec/xscreensaver/rotzoomer
/V3/usr/libexec/xscreensaver/rubik
/V3/usr/libexec/xscreensaver/rubikblocks
/V3/usr/libexec/xscreensaver/sballs
/V3/usr/libexec/xscreensaver/scooter
/V3/usr/libexec/xscreensaver/shadebobs
/V3/usr/libexec/xscreensaver/sierpinski
/V3/usr/libexec/xscreensaver/sierpinski3d
/V3/usr/libexec/xscreensaver/skytentacles
/V3/usr/libexec/xscreensaver/slidescreen
/V3/usr/libexec/xscreensaver/slip
/V3/usr/libexec/xscreensaver/sonar
/V3/usr/libexec/xscreensaver/speedmine
/V3/usr/libexec/xscreensaver/sphereeversion
/V3/usr/libexec/xscreensaver/spheremonics
/V3/usr/libexec/xscreensaver/splitflap
/V3/usr/libexec/xscreensaver/splodesic
/V3/usr/libexec/xscreensaver/spotlight
/V3/usr/libexec/xscreensaver/sproingies
/V3/usr/libexec/xscreensaver/squiral
/V3/usr/libexec/xscreensaver/squirtorus
/V3/usr/libexec/xscreensaver/stairs
/V3/usr/libexec/xscreensaver/starfish
/V3/usr/libexec/xscreensaver/starwars
/V3/usr/libexec/xscreensaver/stonerview
/V3/usr/libexec/xscreensaver/strange
/V3/usr/libexec/xscreensaver/substrate
/V3/usr/libexec/xscreensaver/superquadrics
/V3/usr/libexec/xscreensaver/surfaces
/V3/usr/libexec/xscreensaver/swirl
/V3/usr/libexec/xscreensaver/tangram
/V3/usr/libexec/xscreensaver/tessellimage
/V3/usr/libexec/xscreensaver/timetunnel
/V3/usr/libexec/xscreensaver/topblock
/V3/usr/libexec/xscreensaver/triangle
/V3/usr/libexec/xscreensaver/tronbit
/V3/usr/libexec/xscreensaver/truchet
/V3/usr/libexec/xscreensaver/twang
/V3/usr/libexec/xscreensaver/unicrud
/V3/usr/libexec/xscreensaver/unknownpleasures
/V3/usr/libexec/xscreensaver/vermiculate
/V3/usr/libexec/xscreensaver/vfeedback
/V3/usr/libexec/xscreensaver/vigilance
/V3/usr/libexec/xscreensaver/voronoi
/V3/usr/libexec/xscreensaver/wander
/V3/usr/libexec/xscreensaver/whirlwindwarp
/V3/usr/libexec/xscreensaver/winduprobot
/V3/usr/libexec/xscreensaver/wormhole
/V3/usr/libexec/xscreensaver/xanalogtv
/V3/usr/libexec/xscreensaver/xflame
/V3/usr/libexec/xscreensaver/xjack
/V3/usr/libexec/xscreensaver/xlyap
/V3/usr/libexec/xscreensaver/xmatrix
/V3/usr/libexec/xscreensaver/xrayswarm
/V3/usr/libexec/xscreensaver/xspirograph
/V3/usr/libexec/xscreensaver/zoom
/usr/libexec/xscreensaver/abstractile
/usr/libexec/xscreensaver/anemone
/usr/libexec/xscreensaver/anemotaxis
/usr/libexec/xscreensaver/antinspect
/usr/libexec/xscreensaver/antmaze
/usr/libexec/xscreensaver/antspotlight
/usr/libexec/xscreensaver/apollonian
/usr/libexec/xscreensaver/apple2
/usr/libexec/xscreensaver/atlantis
/usr/libexec/xscreensaver/attraction
/usr/libexec/xscreensaver/atunnel
/usr/libexec/xscreensaver/barcode
/usr/libexec/xscreensaver/beats
/usr/libexec/xscreensaver/binaryhorizon
/usr/libexec/xscreensaver/binaryring
/usr/libexec/xscreensaver/blaster
/usr/libexec/xscreensaver/blinkbox
/usr/libexec/xscreensaver/blitspin
/usr/libexec/xscreensaver/blocktube
/usr/libexec/xscreensaver/boing
/usr/libexec/xscreensaver/bouboule
/usr/libexec/xscreensaver/bouncingcow
/usr/libexec/xscreensaver/boxed
/usr/libexec/xscreensaver/boxfit
/usr/libexec/xscreensaver/braid
/usr/libexec/xscreensaver/bsod
/usr/libexec/xscreensaver/bubble3d
/usr/libexec/xscreensaver/bumps
/usr/libexec/xscreensaver/cage
/usr/libexec/xscreensaver/carousel
/usr/libexec/xscreensaver/ccurve
/usr/libexec/xscreensaver/celtic
/usr/libexec/xscreensaver/chompytower
/usr/libexec/xscreensaver/circuit
/usr/libexec/xscreensaver/cityflow
/usr/libexec/xscreensaver/cloudlife
/usr/libexec/xscreensaver/companioncube
/usr/libexec/xscreensaver/compass
/usr/libexec/xscreensaver/coral
/usr/libexec/xscreensaver/covid19
/usr/libexec/xscreensaver/crackberg
/usr/libexec/xscreensaver/crumbler
/usr/libexec/xscreensaver/crystal
/usr/libexec/xscreensaver/cube21
/usr/libexec/xscreensaver/cubenetic
/usr/libexec/xscreensaver/cubestack
/usr/libexec/xscreensaver/cubestorm
/usr/libexec/xscreensaver/cubetwist
/usr/libexec/xscreensaver/cubicgrid
/usr/libexec/xscreensaver/cwaves
/usr/libexec/xscreensaver/cynosure
/usr/libexec/xscreensaver/dangerball
/usr/libexec/xscreensaver/decayscreen
/usr/libexec/xscreensaver/deco
/usr/libexec/xscreensaver/deepstars
/usr/libexec/xscreensaver/deluxe
/usr/libexec/xscreensaver/demon
/usr/libexec/xscreensaver/discoball
/usr/libexec/xscreensaver/discrete
/usr/libexec/xscreensaver/distort
/usr/libexec/xscreensaver/drift
/usr/libexec/xscreensaver/dymaxionmap
/usr/libexec/xscreensaver/endgame
/usr/libexec/xscreensaver/energystream
/usr/libexec/xscreensaver/engine
/usr/libexec/xscreensaver/epicycle
/usr/libexec/xscreensaver/eruption
/usr/libexec/xscreensaver/esper
/usr/libexec/xscreensaver/etruscanvenus
/usr/libexec/xscreensaver/euler2d
/usr/libexec/xscreensaver/fadeplot
/usr/libexec/xscreensaver/fiberlamp
/usr/libexec/xscreensaver/filmleader
/usr/libexec/xscreensaver/fireworkx
/usr/libexec/xscreensaver/flame
/usr/libexec/xscreensaver/flipflop
/usr/libexec/xscreensaver/flipscreen3d
/usr/libexec/xscreensaver/fliptext
/usr/libexec/xscreensaver/flow
/usr/libexec/xscreensaver/fluidballs
/usr/libexec/xscreensaver/flurry
/usr/libexec/xscreensaver/flyingtoasters
/usr/libexec/xscreensaver/fontglide
/usr/libexec/xscreensaver/fuzzyflakes
/usr/libexec/xscreensaver/galaxy
/usr/libexec/xscreensaver/gears
/usr/libexec/xscreensaver/geodesic
/usr/libexec/xscreensaver/geodesicgears
/usr/libexec/xscreensaver/gflux
/usr/libexec/xscreensaver/gibson
/usr/libexec/xscreensaver/glblur
/usr/libexec/xscreensaver/glcells
/usr/libexec/xscreensaver/gleidescope
/usr/libexec/xscreensaver/glhanoi
/usr/libexec/xscreensaver/glitchpeg
/usr/libexec/xscreensaver/glknots
/usr/libexec/xscreensaver/glmatrix
/usr/libexec/xscreensaver/glplanet
/usr/libexec/xscreensaver/glschool
/usr/libexec/xscreensaver/glslideshow
/usr/libexec/xscreensaver/glsnake
/usr/libexec/xscreensaver/gltext
/usr/libexec/xscreensaver/goop
/usr/libexec/xscreensaver/grav
/usr/libexec/xscreensaver/gravitywell
/usr/libexec/xscreensaver/greynetic
/usr/libexec/xscreensaver/halftone
/usr/libexec/xscreensaver/halo
/usr/libexec/xscreensaver/handsy
/usr/libexec/xscreensaver/headroom
/usr/libexec/xscreensaver/helix
/usr/libexec/xscreensaver/hexadrop
/usr/libexec/xscreensaver/hexstrut
/usr/libexec/xscreensaver/hilbert
/usr/libexec/xscreensaver/hopalong
/usr/libexec/xscreensaver/hydrostat
/usr/libexec/xscreensaver/hypertorus
/usr/libexec/xscreensaver/hypnowheel
/usr/libexec/xscreensaver/ifs
/usr/libexec/xscreensaver/imsmap
/usr/libexec/xscreensaver/interaggregate
/usr/libexec/xscreensaver/interference
/usr/libexec/xscreensaver/intermomentary
/usr/libexec/xscreensaver/jigglypuff
/usr/libexec/xscreensaver/jigsaw
/usr/libexec/xscreensaver/juggler3d
/usr/libexec/xscreensaver/julia
/usr/libexec/xscreensaver/kaleidescope
/usr/libexec/xscreensaver/kaleidocycle
/usr/libexec/xscreensaver/klein
/usr/libexec/xscreensaver/kumppa
/usr/libexec/xscreensaver/lament
/usr/libexec/xscreensaver/lavalite
/usr/libexec/xscreensaver/lcdscrub
/usr/libexec/xscreensaver/lockward
/usr/libexec/xscreensaver/loop
/usr/libexec/xscreensaver/m6502
/usr/libexec/xscreensaver/mapscroller
/usr/libexec/xscreensaver/mapscroller.pl
/usr/libexec/xscreensaver/marbling
/usr/libexec/xscreensaver/maze
/usr/libexec/xscreensaver/maze3d
/usr/libexec/xscreensaver/memscroller
/usr/libexec/xscreensaver/menger
/usr/libexec/xscreensaver/metaballs
/usr/libexec/xscreensaver/mirrorblob
/usr/libexec/xscreensaver/moebius
/usr/libexec/xscreensaver/moebiusgears
/usr/libexec/xscreensaver/moire
/usr/libexec/xscreensaver/moire2
/usr/libexec/xscreensaver/molecule
/usr/libexec/xscreensaver/morph3d
/usr/libexec/xscreensaver/mountain
/usr/libexec/xscreensaver/munch
/usr/libexec/xscreensaver/nakagin
/usr/libexec/xscreensaver/nerverot
/usr/libexec/xscreensaver/noof
/usr/libexec/xscreensaver/noseguy
/usr/libexec/xscreensaver/pacman
/usr/libexec/xscreensaver/pedal
/usr/libexec/xscreensaver/peepers
/usr/libexec/xscreensaver/penetrate
/usr/libexec/xscreensaver/penrose
/usr/libexec/xscreensaver/petri
/usr/libexec/xscreensaver/phosphor
/usr/libexec/xscreensaver/photopile
/usr/libexec/xscreensaver/piecewise
/usr/libexec/xscreensaver/pinion
/usr/libexec/xscreensaver/pipes
/usr/libexec/xscreensaver/polyhedra
/usr/libexec/xscreensaver/polyominoes
/usr/libexec/xscreensaver/polytopes
/usr/libexec/xscreensaver/pong
/usr/libexec/xscreensaver/popsquares
/usr/libexec/xscreensaver/projectiveplane
/usr/libexec/xscreensaver/providence
/usr/libexec/xscreensaver/pulsar
/usr/libexec/xscreensaver/pyro
/usr/libexec/xscreensaver/qix
/usr/libexec/xscreensaver/quasicrystal
/usr/libexec/xscreensaver/queens
/usr/libexec/xscreensaver/raverhoop
/usr/libexec/xscreensaver/razzledazzle
/usr/libexec/xscreensaver/rdbomb
/usr/libexec/xscreensaver/ripples
/usr/libexec/xscreensaver/rocks
/usr/libexec/xscreensaver/romanboy
/usr/libexec/xscreensaver/rorschach
/usr/libexec/xscreensaver/rotzoomer
/usr/libexec/xscreensaver/rubik
/usr/libexec/xscreensaver/rubikblocks
/usr/libexec/xscreensaver/sballs
/usr/libexec/xscreensaver/scooter
/usr/libexec/xscreensaver/shadebobs
/usr/libexec/xscreensaver/sierpinski
/usr/libexec/xscreensaver/sierpinski3d
/usr/libexec/xscreensaver/skytentacles
/usr/libexec/xscreensaver/slidescreen
/usr/libexec/xscreensaver/slip
/usr/libexec/xscreensaver/sonar
/usr/libexec/xscreensaver/speedmine
/usr/libexec/xscreensaver/sphereeversion
/usr/libexec/xscreensaver/spheremonics
/usr/libexec/xscreensaver/splitflap
/usr/libexec/xscreensaver/splodesic
/usr/libexec/xscreensaver/spotlight
/usr/libexec/xscreensaver/sproingies
/usr/libexec/xscreensaver/squiral
/usr/libexec/xscreensaver/squirtorus
/usr/libexec/xscreensaver/stairs
/usr/libexec/xscreensaver/starfish
/usr/libexec/xscreensaver/starwars
/usr/libexec/xscreensaver/stonerview
/usr/libexec/xscreensaver/strange
/usr/libexec/xscreensaver/substrate
/usr/libexec/xscreensaver/superquadrics
/usr/libexec/xscreensaver/surfaces
/usr/libexec/xscreensaver/swirl
/usr/libexec/xscreensaver/tangram
/usr/libexec/xscreensaver/tessellimage
/usr/libexec/xscreensaver/timetunnel
/usr/libexec/xscreensaver/topblock
/usr/libexec/xscreensaver/triangle
/usr/libexec/xscreensaver/tronbit
/usr/libexec/xscreensaver/truchet
/usr/libexec/xscreensaver/twang
/usr/libexec/xscreensaver/unicrud
/usr/libexec/xscreensaver/unknownpleasures
/usr/libexec/xscreensaver/vermiculate
/usr/libexec/xscreensaver/vfeedback
/usr/libexec/xscreensaver/vidwhacker
/usr/libexec/xscreensaver/vigilance
/usr/libexec/xscreensaver/voronoi
/usr/libexec/xscreensaver/wander
/usr/libexec/xscreensaver/webcollage
/usr/libexec/xscreensaver/whirlwindwarp
/usr/libexec/xscreensaver/winduprobot
/usr/libexec/xscreensaver/wormhole
/usr/libexec/xscreensaver/xanalogtv
/usr/libexec/xscreensaver/xflame
/usr/libexec/xscreensaver/xjack
/usr/libexec/xscreensaver/xlyap
/usr/libexec/xscreensaver/xmatrix
/usr/libexec/xscreensaver/xrayswarm
/usr/libexec/xscreensaver/xspirograph
/usr/libexec/xscreensaver/zoom
/usr/share/xscreensaver/config/abstractile.xml
/usr/share/xscreensaver/config/anemone.xml
/usr/share/xscreensaver/config/anemotaxis.xml
/usr/share/xscreensaver/config/antinspect.xml
/usr/share/xscreensaver/config/antmaze.xml
/usr/share/xscreensaver/config/antspotlight.xml
/usr/share/xscreensaver/config/apollonian.xml
/usr/share/xscreensaver/config/apple2.xml
/usr/share/xscreensaver/config/atlantis.xml
/usr/share/xscreensaver/config/attraction.xml
/usr/share/xscreensaver/config/atunnel.xml
/usr/share/xscreensaver/config/barcode.xml
/usr/share/xscreensaver/config/beats.xml
/usr/share/xscreensaver/config/binaryhorizon.xml
/usr/share/xscreensaver/config/binaryring.xml
/usr/share/xscreensaver/config/blaster.xml
/usr/share/xscreensaver/config/blinkbox.xml
/usr/share/xscreensaver/config/blitspin.xml
/usr/share/xscreensaver/config/blocktube.xml
/usr/share/xscreensaver/config/boing.xml
/usr/share/xscreensaver/config/bouboule.xml
/usr/share/xscreensaver/config/bouncingcow.xml
/usr/share/xscreensaver/config/boxed.xml
/usr/share/xscreensaver/config/boxfit.xml
/usr/share/xscreensaver/config/braid.xml
/usr/share/xscreensaver/config/bsod.xml
/usr/share/xscreensaver/config/bubble3d.xml
/usr/share/xscreensaver/config/bumps.xml
/usr/share/xscreensaver/config/cage.xml
/usr/share/xscreensaver/config/carousel.xml
/usr/share/xscreensaver/config/ccurve.xml
/usr/share/xscreensaver/config/celtic.xml
/usr/share/xscreensaver/config/chompytower.xml
/usr/share/xscreensaver/config/circuit.xml
/usr/share/xscreensaver/config/cityflow.xml
/usr/share/xscreensaver/config/cloudlife.xml
/usr/share/xscreensaver/config/companioncube.xml
/usr/share/xscreensaver/config/compass.xml
/usr/share/xscreensaver/config/coral.xml
/usr/share/xscreensaver/config/covid19.xml
/usr/share/xscreensaver/config/crackberg.xml
/usr/share/xscreensaver/config/crumbler.xml
/usr/share/xscreensaver/config/crystal.xml
/usr/share/xscreensaver/config/cube21.xml
/usr/share/xscreensaver/config/cubenetic.xml
/usr/share/xscreensaver/config/cubestack.xml
/usr/share/xscreensaver/config/cubestorm.xml
/usr/share/xscreensaver/config/cubetwist.xml
/usr/share/xscreensaver/config/cubicgrid.xml
/usr/share/xscreensaver/config/cwaves.xml
/usr/share/xscreensaver/config/cynosure.xml
/usr/share/xscreensaver/config/dangerball.xml
/usr/share/xscreensaver/config/decayscreen.xml
/usr/share/xscreensaver/config/deco.xml
/usr/share/xscreensaver/config/deepstars.xml
/usr/share/xscreensaver/config/deluxe.xml
/usr/share/xscreensaver/config/demon.xml
/usr/share/xscreensaver/config/discoball.xml
/usr/share/xscreensaver/config/discrete.xml
/usr/share/xscreensaver/config/distort.xml
/usr/share/xscreensaver/config/drift.xml
/usr/share/xscreensaver/config/dymaxionmap.xml
/usr/share/xscreensaver/config/endgame.xml
/usr/share/xscreensaver/config/energystream.xml
/usr/share/xscreensaver/config/engine.xml
/usr/share/xscreensaver/config/epicycle.xml
/usr/share/xscreensaver/config/eruption.xml
/usr/share/xscreensaver/config/esper.xml
/usr/share/xscreensaver/config/etruscanvenus.xml
/usr/share/xscreensaver/config/euler2d.xml
/usr/share/xscreensaver/config/fadeplot.xml
/usr/share/xscreensaver/config/fiberlamp.xml
/usr/share/xscreensaver/config/filmleader.xml
/usr/share/xscreensaver/config/fireworkx.xml
/usr/share/xscreensaver/config/flame.xml
/usr/share/xscreensaver/config/flipflop.xml
/usr/share/xscreensaver/config/flipscreen3d.xml
/usr/share/xscreensaver/config/fliptext.xml
/usr/share/xscreensaver/config/flow.xml
/usr/share/xscreensaver/config/fluidballs.xml
/usr/share/xscreensaver/config/flurry.xml
/usr/share/xscreensaver/config/flyingtoasters.xml
/usr/share/xscreensaver/config/fontglide.xml
/usr/share/xscreensaver/config/fuzzyflakes.xml
/usr/share/xscreensaver/config/galaxy.xml
/usr/share/xscreensaver/config/gears.xml
/usr/share/xscreensaver/config/geodesic.xml
/usr/share/xscreensaver/config/geodesicgears.xml
/usr/share/xscreensaver/config/gflux.xml
/usr/share/xscreensaver/config/gibson.xml
/usr/share/xscreensaver/config/glblur.xml
/usr/share/xscreensaver/config/glcells.xml
/usr/share/xscreensaver/config/gleidescope.xml
/usr/share/xscreensaver/config/glhanoi.xml
/usr/share/xscreensaver/config/glitchpeg.xml
/usr/share/xscreensaver/config/glknots.xml
/usr/share/xscreensaver/config/glmatrix.xml
/usr/share/xscreensaver/config/glplanet.xml
/usr/share/xscreensaver/config/glschool.xml
/usr/share/xscreensaver/config/glslideshow.xml
/usr/share/xscreensaver/config/glsnake.xml
/usr/share/xscreensaver/config/gltext.xml
/usr/share/xscreensaver/config/goop.xml
/usr/share/xscreensaver/config/grav.xml
/usr/share/xscreensaver/config/gravitywell.xml
/usr/share/xscreensaver/config/greynetic.xml
/usr/share/xscreensaver/config/halftone.xml
/usr/share/xscreensaver/config/halo.xml
/usr/share/xscreensaver/config/handsy.xml
/usr/share/xscreensaver/config/headroom.xml
/usr/share/xscreensaver/config/helix.xml
/usr/share/xscreensaver/config/hexadrop.xml
/usr/share/xscreensaver/config/hexstrut.xml
/usr/share/xscreensaver/config/hilbert.xml
/usr/share/xscreensaver/config/hopalong.xml
/usr/share/xscreensaver/config/hydrostat.xml
/usr/share/xscreensaver/config/hypertorus.xml
/usr/share/xscreensaver/config/hypnowheel.xml
/usr/share/xscreensaver/config/ifs.xml
/usr/share/xscreensaver/config/imsmap.xml
/usr/share/xscreensaver/config/interaggregate.xml
/usr/share/xscreensaver/config/interference.xml
/usr/share/xscreensaver/config/intermomentary.xml
/usr/share/xscreensaver/config/jigglypuff.xml
/usr/share/xscreensaver/config/jigsaw.xml
/usr/share/xscreensaver/config/juggler3d.xml
/usr/share/xscreensaver/config/julia.xml
/usr/share/xscreensaver/config/kaleidescope.xml
/usr/share/xscreensaver/config/kaleidocycle.xml
/usr/share/xscreensaver/config/klein.xml
/usr/share/xscreensaver/config/kumppa.xml
/usr/share/xscreensaver/config/lament.xml
/usr/share/xscreensaver/config/lavalite.xml
/usr/share/xscreensaver/config/lcdscrub.xml
/usr/share/xscreensaver/config/lockward.xml
/usr/share/xscreensaver/config/loop.xml
/usr/share/xscreensaver/config/m6502.xml
/usr/share/xscreensaver/config/mapscroller.xml
/usr/share/xscreensaver/config/marbling.xml
/usr/share/xscreensaver/config/maze.xml
/usr/share/xscreensaver/config/maze3d.xml
/usr/share/xscreensaver/config/memscroller.xml
/usr/share/xscreensaver/config/menger.xml
/usr/share/xscreensaver/config/metaballs.xml
/usr/share/xscreensaver/config/mirrorblob.xml
/usr/share/xscreensaver/config/moebius.xml
/usr/share/xscreensaver/config/moebiusgears.xml
/usr/share/xscreensaver/config/moire.xml
/usr/share/xscreensaver/config/moire2.xml
/usr/share/xscreensaver/config/molecule.xml
/usr/share/xscreensaver/config/morph3d.xml
/usr/share/xscreensaver/config/mountain.xml
/usr/share/xscreensaver/config/munch.xml
/usr/share/xscreensaver/config/nakagin.xml
/usr/share/xscreensaver/config/nerverot.xml
/usr/share/xscreensaver/config/noof.xml
/usr/share/xscreensaver/config/noseguy.xml
/usr/share/xscreensaver/config/pacman.xml
/usr/share/xscreensaver/config/pedal.xml
/usr/share/xscreensaver/config/peepers.xml
/usr/share/xscreensaver/config/penetrate.xml
/usr/share/xscreensaver/config/penrose.xml
/usr/share/xscreensaver/config/petri.xml
/usr/share/xscreensaver/config/phosphor.xml
/usr/share/xscreensaver/config/photopile.xml
/usr/share/xscreensaver/config/piecewise.xml
/usr/share/xscreensaver/config/pinion.xml
/usr/share/xscreensaver/config/pipes.xml
/usr/share/xscreensaver/config/polyhedra.xml
/usr/share/xscreensaver/config/polyominoes.xml
/usr/share/xscreensaver/config/polytopes.xml
/usr/share/xscreensaver/config/pong.xml
/usr/share/xscreensaver/config/popsquares.xml
/usr/share/xscreensaver/config/projectiveplane.xml
/usr/share/xscreensaver/config/providence.xml
/usr/share/xscreensaver/config/pulsar.xml
/usr/share/xscreensaver/config/pyro.xml
/usr/share/xscreensaver/config/qix.xml
/usr/share/xscreensaver/config/quasicrystal.xml
/usr/share/xscreensaver/config/queens.xml
/usr/share/xscreensaver/config/raverhoop.xml
/usr/share/xscreensaver/config/razzledazzle.xml
/usr/share/xscreensaver/config/rdbomb.xml
/usr/share/xscreensaver/config/ripples.xml
/usr/share/xscreensaver/config/rocks.xml
/usr/share/xscreensaver/config/romanboy.xml
/usr/share/xscreensaver/config/rorschach.xml
/usr/share/xscreensaver/config/rotzoomer.xml
/usr/share/xscreensaver/config/rubik.xml
/usr/share/xscreensaver/config/rubikblocks.xml
/usr/share/xscreensaver/config/sballs.xml
/usr/share/xscreensaver/config/scooter.xml
/usr/share/xscreensaver/config/shadebobs.xml
/usr/share/xscreensaver/config/sierpinski.xml
/usr/share/xscreensaver/config/sierpinski3d.xml
/usr/share/xscreensaver/config/skytentacles.xml
/usr/share/xscreensaver/config/slidescreen.xml
/usr/share/xscreensaver/config/slip.xml
/usr/share/xscreensaver/config/sonar.xml
/usr/share/xscreensaver/config/speedmine.xml
/usr/share/xscreensaver/config/sphereeversion.xml
/usr/share/xscreensaver/config/spheremonics.xml
/usr/share/xscreensaver/config/splitflap.xml
/usr/share/xscreensaver/config/splodesic.xml
/usr/share/xscreensaver/config/spotlight.xml
/usr/share/xscreensaver/config/sproingies.xml
/usr/share/xscreensaver/config/squiral.xml
/usr/share/xscreensaver/config/squirtorus.xml
/usr/share/xscreensaver/config/stairs.xml
/usr/share/xscreensaver/config/starfish.xml
/usr/share/xscreensaver/config/starwars.xml
/usr/share/xscreensaver/config/stonerview.xml
/usr/share/xscreensaver/config/strange.xml
/usr/share/xscreensaver/config/substrate.xml
/usr/share/xscreensaver/config/superquadrics.xml
/usr/share/xscreensaver/config/surfaces.xml
/usr/share/xscreensaver/config/swirl.xml
/usr/share/xscreensaver/config/tangram.xml
/usr/share/xscreensaver/config/tessellimage.xml
/usr/share/xscreensaver/config/timetunnel.xml
/usr/share/xscreensaver/config/topblock.xml
/usr/share/xscreensaver/config/triangle.xml
/usr/share/xscreensaver/config/tronbit.xml
/usr/share/xscreensaver/config/truchet.xml
/usr/share/xscreensaver/config/twang.xml
/usr/share/xscreensaver/config/unicrud.xml
/usr/share/xscreensaver/config/unknownpleasures.xml
/usr/share/xscreensaver/config/vermiculate.xml
/usr/share/xscreensaver/config/vfeedback.xml
/usr/share/xscreensaver/config/vidwhacker.xml
/usr/share/xscreensaver/config/vigilance.xml
/usr/share/xscreensaver/config/voronoi.xml
/usr/share/xscreensaver/config/wander.xml
/usr/share/xscreensaver/config/webcollage.xml
/usr/share/xscreensaver/config/whirlwindwarp.xml
/usr/share/xscreensaver/config/winduprobot.xml
/usr/share/xscreensaver/config/wormhole.xml
/usr/share/xscreensaver/config/xanalogtv.xml
/usr/share/xscreensaver/config/xflame.xml
/usr/share/xscreensaver/config/xjack.xml
/usr/share/xscreensaver/config/xlyap.xml
/usr/share/xscreensaver/config/xmatrix.xml
/usr/share/xscreensaver/config/xrayswarm.xml
/usr/share/xscreensaver/config/xspirograph.xml
/usr/share/xscreensaver/config/zoom.xml

%files libexec
%defattr(-,root,root,-)
/V3/usr/libexec/xscreensaver/cubocteversion
/V3/usr/libexec/xscreensaver/droste
/V3/usr/libexec/xscreensaver/hextrail
/V3/usr/libexec/xscreensaver/papercube
/V3/usr/libexec/xscreensaver/skulloop
/V3/usr/libexec/xscreensaver/webcollage-helper
/V3/usr/libexec/xscreensaver/xscreensaver-auth
/V3/usr/libexec/xscreensaver/xscreensaver-getimage
/V3/usr/libexec/xscreensaver/xscreensaver-gfx
/V3/usr/libexec/xscreensaver/xscreensaver-gl-visual
/V3/usr/libexec/xscreensaver/xscreensaver-systemd
/usr/libexec/xscreensaver/cubocteversion
/usr/libexec/xscreensaver/droste
/usr/libexec/xscreensaver/hextrail
/usr/libexec/xscreensaver/papercube
/usr/libexec/xscreensaver/skulloop
/usr/libexec/xscreensaver/webcollage-helper
/usr/libexec/xscreensaver/xscreensaver-auth
/usr/libexec/xscreensaver/xscreensaver-getimage
/usr/libexec/xscreensaver/xscreensaver-getimage-file
/usr/libexec/xscreensaver/xscreensaver-getimage-video
/usr/libexec/xscreensaver/xscreensaver-gfx
/usr/libexec/xscreensaver/xscreensaver-gl-visual
/usr/libexec/xscreensaver/xscreensaver-systemd
/usr/libexec/xscreensaver/xscreensaver-text

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/xscreensaver-command.1
/usr/share/man/man1/xscreensaver-demo.1
/usr/share/man/man1/xscreensaver-settings.1
/usr/share/man/man1/xscreensaver.1
/usr/share/man/man6/abstractile.6
/usr/share/man/man6/anemone.6
/usr/share/man/man6/anemotaxis.6
/usr/share/man/man6/antinspect.6
/usr/share/man/man6/antmaze.6
/usr/share/man/man6/antspotlight.6
/usr/share/man/man6/apollonian.6
/usr/share/man/man6/apple2.6
/usr/share/man/man6/atlantis.6
/usr/share/man/man6/attraction.6
/usr/share/man/man6/atunnel.6
/usr/share/man/man6/barcode.6
/usr/share/man/man6/beats.6
/usr/share/man/man6/binaryhorizon.6
/usr/share/man/man6/binaryring.6
/usr/share/man/man6/blaster.6
/usr/share/man/man6/blinkbox.6
/usr/share/man/man6/blitspin.6
/usr/share/man/man6/blocktube.6
/usr/share/man/man6/boing.6
/usr/share/man/man6/bouboule.6
/usr/share/man/man6/bouncingcow.6
/usr/share/man/man6/boxed.6
/usr/share/man/man6/boxfit.6
/usr/share/man/man6/braid.6
/usr/share/man/man6/bsod.6
/usr/share/man/man6/bubble3d.6
/usr/share/man/man6/bumps.6
/usr/share/man/man6/cage.6
/usr/share/man/man6/carousel.6
/usr/share/man/man6/ccurve.6
/usr/share/man/man6/celtic.6
/usr/share/man/man6/chompytower.6
/usr/share/man/man6/circuit.6
/usr/share/man/man6/cityflow.6
/usr/share/man/man6/cloudlife.6
/usr/share/man/man6/companioncube.6
/usr/share/man/man6/compass.6
/usr/share/man/man6/coral.6
/usr/share/man/man6/covid19.6
/usr/share/man/man6/crackberg.6
/usr/share/man/man6/crumbler.6
/usr/share/man/man6/crystal.6
/usr/share/man/man6/cube21.6
/usr/share/man/man6/cubenetic.6
/usr/share/man/man6/cubestack.6
/usr/share/man/man6/cubestorm.6
/usr/share/man/man6/cubetwist.6
/usr/share/man/man6/cubicgrid.6
/usr/share/man/man6/cubocteversion.6
/usr/share/man/man6/cwaves.6
/usr/share/man/man6/cynosure.6
/usr/share/man/man6/dangerball.6
/usr/share/man/man6/decayscreen.6
/usr/share/man/man6/deco.6
/usr/share/man/man6/deepstars.6
/usr/share/man/man6/deluxe.6
/usr/share/man/man6/demon.6
/usr/share/man/man6/discoball.6
/usr/share/man/man6/discrete.6
/usr/share/man/man6/distort.6
/usr/share/man/man6/drift.6
/usr/share/man/man6/droste.6
/usr/share/man/man6/dymaxionmap.6
/usr/share/man/man6/endgame.6
/usr/share/man/man6/energystream.6
/usr/share/man/man6/engine.6
/usr/share/man/man6/epicycle.6
/usr/share/man/man6/eruption.6
/usr/share/man/man6/esper.6
/usr/share/man/man6/etruscanvenus.6
/usr/share/man/man6/euler2d.6
/usr/share/man/man6/extrusion.6
/usr/share/man/man6/fadeplot.6
/usr/share/man/man6/fiberlamp.6
/usr/share/man/man6/filmleader.6
/usr/share/man/man6/fireworkx.6
/usr/share/man/man6/flame.6
/usr/share/man/man6/flipflop.6
/usr/share/man/man6/flipscreen3d.6
/usr/share/man/man6/fliptext.6
/usr/share/man/man6/flow.6
/usr/share/man/man6/fluidballs.6
/usr/share/man/man6/flurry.6
/usr/share/man/man6/flyingtoasters.6
/usr/share/man/man6/fontglide.6
/usr/share/man/man6/fuzzyflakes.6
/usr/share/man/man6/galaxy.6
/usr/share/man/man6/gears.6
/usr/share/man/man6/geodesic.6
/usr/share/man/man6/geodesicgears.6
/usr/share/man/man6/gflux.6
/usr/share/man/man6/gibson.6
/usr/share/man/man6/glblur.6
/usr/share/man/man6/glcells.6
/usr/share/man/man6/gleidescope.6
/usr/share/man/man6/glhanoi.6
/usr/share/man/man6/glitchpeg.6
/usr/share/man/man6/glknots.6
/usr/share/man/man6/glmatrix.6
/usr/share/man/man6/glplanet.6
/usr/share/man/man6/glschool.6
/usr/share/man/man6/glslideshow.6
/usr/share/man/man6/glsnake.6
/usr/share/man/man6/gltext.6
/usr/share/man/man6/goop.6
/usr/share/man/man6/grav.6
/usr/share/man/man6/gravitywell.6
/usr/share/man/man6/greynetic.6
/usr/share/man/man6/halftone.6
/usr/share/man/man6/halo.6
/usr/share/man/man6/handsy.6
/usr/share/man/man6/headroom.6
/usr/share/man/man6/helix.6
/usr/share/man/man6/hexadrop.6
/usr/share/man/man6/hexstrut.6
/usr/share/man/man6/hextrail.6
/usr/share/man/man6/hilbert.6
/usr/share/man/man6/hopalong.6
/usr/share/man/man6/hydrostat.6
/usr/share/man/man6/hypertorus.6
/usr/share/man/man6/hypnowheel.6
/usr/share/man/man6/ifs.6
/usr/share/man/man6/imsmap.6
/usr/share/man/man6/interaggregate.6
/usr/share/man/man6/interference.6
/usr/share/man/man6/intermomentary.6
/usr/share/man/man6/jigglypuff.6
/usr/share/man/man6/jigsaw.6
/usr/share/man/man6/juggler3d.6
/usr/share/man/man6/julia.6
/usr/share/man/man6/kaleidescope.6
/usr/share/man/man6/kaleidocycle.6
/usr/share/man/man6/klein.6
/usr/share/man/man6/kumppa.6
/usr/share/man/man6/lament.6
/usr/share/man/man6/lavalite.6
/usr/share/man/man6/lcdscrub.6
/usr/share/man/man6/lockward.6
/usr/share/man/man6/loop.6
/usr/share/man/man6/mapscroller.6
/usr/share/man/man6/marbling.6
/usr/share/man/man6/maze.6
/usr/share/man/man6/maze3d.6
/usr/share/man/man6/memscroller.6
/usr/share/man/man6/menger.6
/usr/share/man/man6/metaballs.6
/usr/share/man/man6/mirrorblob.6
/usr/share/man/man6/moebius.6
/usr/share/man/man6/moebiusgears.6
/usr/share/man/man6/moire.6
/usr/share/man/man6/moire2.6
/usr/share/man/man6/molecule.6
/usr/share/man/man6/morph3d.6
/usr/share/man/man6/mountain.6
/usr/share/man/man6/munch.6
/usr/share/man/man6/nakagin.6
/usr/share/man/man6/nerverot.6
/usr/share/man/man6/noof.6
/usr/share/man/man6/noseguy.6
/usr/share/man/man6/pacman.6
/usr/share/man/man6/papercube.6
/usr/share/man/man6/pedal.6
/usr/share/man/man6/peepers.6
/usr/share/man/man6/penetrate.6
/usr/share/man/man6/penrose.6
/usr/share/man/man6/petri.6
/usr/share/man/man6/phosphor.6
/usr/share/man/man6/photopile.6
/usr/share/man/man6/piecewise.6
/usr/share/man/man6/pinion.6
/usr/share/man/man6/pipes.6
/usr/share/man/man6/polyhedra.6
/usr/share/man/man6/polyominoes.6
/usr/share/man/man6/polytopes.6
/usr/share/man/man6/pong.6
/usr/share/man/man6/projectiveplane.6
/usr/share/man/man6/providence.6
/usr/share/man/man6/pulsar.6
/usr/share/man/man6/pyro.6
/usr/share/man/man6/qix.6
/usr/share/man/man6/quasicrystal.6
/usr/share/man/man6/queens.6
/usr/share/man/man6/raverhoop.6
/usr/share/man/man6/razzledazzle.6
/usr/share/man/man6/rdbomb.6
/usr/share/man/man6/ripples.6
/usr/share/man/man6/rocks.6
/usr/share/man/man6/romanboy.6
/usr/share/man/man6/rorschach.6
/usr/share/man/man6/rotzoomer.6
/usr/share/man/man6/rubik.6
/usr/share/man/man6/rubikblocks.6
/usr/share/man/man6/sballs.6
/usr/share/man/man6/scooter.6
/usr/share/man/man6/shadebobs.6
/usr/share/man/man6/sierpinski.6
/usr/share/man/man6/sierpinski3d.6
/usr/share/man/man6/skulloop.6
/usr/share/man/man6/skytentacles.6
/usr/share/man/man6/slidescreen.6
/usr/share/man/man6/slip.6
/usr/share/man/man6/sonar.6
/usr/share/man/man6/speedmine.6
/usr/share/man/man6/sphereeversion.6
/usr/share/man/man6/spheremonics.6
/usr/share/man/man6/splitflap.6
/usr/share/man/man6/splodesic.6
/usr/share/man/man6/spotlight.6
/usr/share/man/man6/sproingies.6
/usr/share/man/man6/squiral.6
/usr/share/man/man6/squirtorus.6
/usr/share/man/man6/stairs.6
/usr/share/man/man6/starfish.6
/usr/share/man/man6/starwars.6
/usr/share/man/man6/stonerview.6
/usr/share/man/man6/strange.6
/usr/share/man/man6/substrate.6
/usr/share/man/man6/superquadrics.6
/usr/share/man/man6/surfaces.6
/usr/share/man/man6/swirl.6
/usr/share/man/man6/tangram.6
/usr/share/man/man6/tessellimage.6
/usr/share/man/man6/timetunnel.6
/usr/share/man/man6/topblock.6
/usr/share/man/man6/triangle.6
/usr/share/man/man6/tronbit.6
/usr/share/man/man6/truchet.6
/usr/share/man/man6/twang.6
/usr/share/man/man6/unicrud.6
/usr/share/man/man6/unknownpleasures.6
/usr/share/man/man6/vermiculate.6
/usr/share/man/man6/vfeedback.6
/usr/share/man/man6/vidwhacker.6
/usr/share/man/man6/vigilance.6
/usr/share/man/man6/voronoi.6
/usr/share/man/man6/wander.6
/usr/share/man/man6/webcollage.6
/usr/share/man/man6/whirlwindwarp.6
/usr/share/man/man6/winduprobot.6
/usr/share/man/man6/wormhole.6
/usr/share/man/man6/xanalogtv.6
/usr/share/man/man6/xflame.6
/usr/share/man/man6/xjack.6
/usr/share/man/man6/xlyap.6
/usr/share/man/man6/xmatrix.6
/usr/share/man/man6/xrayswarm.6
/usr/share/man/man6/xscreensaver-auth.6
/usr/share/man/man6/xscreensaver-getimage-file.6
/usr/share/man/man6/xscreensaver-getimage-video.6
/usr/share/man/man6/xscreensaver-getimage.6
/usr/share/man/man6/xscreensaver-gfx.6
/usr/share/man/man6/xscreensaver-gl-visual.6
/usr/share/man/man6/xscreensaver-systemd.6
/usr/share/man/man6/xscreensaver-text.6
/usr/share/man/man6/xspirograph.6
/usr/share/man/man6/zoom.6

%files locales -f xscreensaver.lang
%defattr(-,root,root,-)

