#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xscreensaver
Version  : 5.32
Release  : 3
URL      : http://www.jwz.org/xscreensaver/xscreensaver-5.32.tar.gz
Source0  : http://www.jwz.org/xscreensaver/xscreensaver-5.32.tar.gz
Summary  : A minimal installation of xscreensaver.
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause
Requires: xscreensaver-bin
Requires: xscreensaver-locales
Requires: xscreensaver-doc
Requires: xscreensaver-data
BuildRequires : Linux-PAM-dev
BuildRequires : bc
BuildRequires : gdk-pixbuf-dev
BuildRequires : gettext
BuildRequires : glibc-staticdev
BuildRequires : gtk+-dev
BuildRequires : intltool
BuildRequires : libXinerama-dev
BuildRequires : libXmu-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gl)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xi)
BuildRequires : pkgconfig(xpm)
BuildRequires : pkgconfig(xrandr)

%description
A modular screen saver and locker for the X Window System.
More than 200 display modes are included in this package.

%package bin
Summary: bin components for the xscreensaver package.
Group: Binaries
Requires: xscreensaver-data

%description bin
bin components for the xscreensaver package.


%package data
Summary: data components for the xscreensaver package.
Group: Data

%description data
data components for the xscreensaver package.


%package doc
Summary: doc components for the xscreensaver package.
Group: Documentation

%description doc
doc components for the xscreensaver package.


%package locales
Summary: locales components for the xscreensaver package.
Group: Default

%description locales
locales components for the xscreensaver package.


%prep
%setup -q -n xscreensaver-5.32

%build
%configure --disable-static --without-pixbuf --with-xpm --without-gtk --with-pam
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install
%find_lang xscreensaver
## make_install_append content
install -m 00644 -D driver/xscreensaver.pam $RPM_BUILD_ROOT/usr/share/pam.d/xscreensaver
## make_install_append end

%files
%defattr(-,root,root,-)
/usr/lib/X11/app-defaults/XScreenSaver

%files bin
%defattr(-,root,root,-)
/usr/bin/xscreensaver
/usr/bin/xscreensaver-command
/usr/bin/xscreensaver-getimage
/usr/bin/xscreensaver-getimage-file
/usr/bin/xscreensaver-getimage-video
/usr/bin/xscreensaver-text
/usr/libexec/xscreensaver/abstractile
/usr/libexec/xscreensaver/anemone
/usr/libexec/xscreensaver/anemotaxis
/usr/libexec/xscreensaver/apollonian
/usr/libexec/xscreensaver/apple2
/usr/libexec/xscreensaver/attraction
/usr/libexec/xscreensaver/barcode
/usr/libexec/xscreensaver/binaryring
/usr/libexec/xscreensaver/blaster
/usr/libexec/xscreensaver/blitspin
/usr/libexec/xscreensaver/bouboule
/usr/libexec/xscreensaver/boxfit
/usr/libexec/xscreensaver/braid
/usr/libexec/xscreensaver/bsod
/usr/libexec/xscreensaver/bumps
/usr/libexec/xscreensaver/ccurve
/usr/libexec/xscreensaver/celtic
/usr/libexec/xscreensaver/cloudlife
/usr/libexec/xscreensaver/compass
/usr/libexec/xscreensaver/coral
/usr/libexec/xscreensaver/crystal
/usr/libexec/xscreensaver/cwaves
/usr/libexec/xscreensaver/cynosure
/usr/libexec/xscreensaver/decayscreen
/usr/libexec/xscreensaver/deco
/usr/libexec/xscreensaver/deluxe
/usr/libexec/xscreensaver/demon
/usr/libexec/xscreensaver/discrete
/usr/libexec/xscreensaver/distort
/usr/libexec/xscreensaver/drift
/usr/libexec/xscreensaver/epicycle
/usr/libexec/xscreensaver/eruption
/usr/libexec/xscreensaver/euler2d
/usr/libexec/xscreensaver/fadeplot
/usr/libexec/xscreensaver/fiberlamp
/usr/libexec/xscreensaver/fireworkx
/usr/libexec/xscreensaver/flame
/usr/libexec/xscreensaver/flow
/usr/libexec/xscreensaver/fluidballs
/usr/libexec/xscreensaver/fontglide
/usr/libexec/xscreensaver/fuzzyflakes
/usr/libexec/xscreensaver/galaxy
/usr/libexec/xscreensaver/goop
/usr/libexec/xscreensaver/grav
/usr/libexec/xscreensaver/greynetic
/usr/libexec/xscreensaver/halftone
/usr/libexec/xscreensaver/halo
/usr/libexec/xscreensaver/helix
/usr/libexec/xscreensaver/hexadrop
/usr/libexec/xscreensaver/hopalong
/usr/libexec/xscreensaver/ifs
/usr/libexec/xscreensaver/imsmap
/usr/libexec/xscreensaver/interaggregate
/usr/libexec/xscreensaver/interference
/usr/libexec/xscreensaver/intermomentary
/usr/libexec/xscreensaver/julia
/usr/libexec/xscreensaver/kaleidescope
/usr/libexec/xscreensaver/kumppa
/usr/libexec/xscreensaver/lcdscrub
/usr/libexec/xscreensaver/ljlatest
/usr/libexec/xscreensaver/loop
/usr/libexec/xscreensaver/m6502
/usr/libexec/xscreensaver/maze
/usr/libexec/xscreensaver/memscroller
/usr/libexec/xscreensaver/metaballs
/usr/libexec/xscreensaver/moire
/usr/libexec/xscreensaver/moire2
/usr/libexec/xscreensaver/mountain
/usr/libexec/xscreensaver/munch
/usr/libexec/xscreensaver/nerverot
/usr/libexec/xscreensaver/noseguy
/usr/libexec/xscreensaver/pacman
/usr/libexec/xscreensaver/pedal
/usr/libexec/xscreensaver/penetrate
/usr/libexec/xscreensaver/penrose
/usr/libexec/xscreensaver/petri
/usr/libexec/xscreensaver/phosphor
/usr/libexec/xscreensaver/piecewise
/usr/libexec/xscreensaver/polyominoes
/usr/libexec/xscreensaver/pong
/usr/libexec/xscreensaver/popsquares
/usr/libexec/xscreensaver/pyro
/usr/libexec/xscreensaver/qix
/usr/libexec/xscreensaver/rd-bomb
/usr/libexec/xscreensaver/ripples
/usr/libexec/xscreensaver/rocks
/usr/libexec/xscreensaver/rorschach
/usr/libexec/xscreensaver/rotzoomer
/usr/libexec/xscreensaver/shadebobs
/usr/libexec/xscreensaver/sierpinski
/usr/libexec/xscreensaver/slidescreen
/usr/libexec/xscreensaver/slip
/usr/libexec/xscreensaver/speedmine
/usr/libexec/xscreensaver/spotlight
/usr/libexec/xscreensaver/squiral
/usr/libexec/xscreensaver/starfish
/usr/libexec/xscreensaver/strange
/usr/libexec/xscreensaver/substrate
/usr/libexec/xscreensaver/swirl
/usr/libexec/xscreensaver/tessellimage
/usr/libexec/xscreensaver/thornbird
/usr/libexec/xscreensaver/triangle
/usr/libexec/xscreensaver/truchet
/usr/libexec/xscreensaver/twang
/usr/libexec/xscreensaver/vermiculate
/usr/libexec/xscreensaver/vidwhacker
/usr/libexec/xscreensaver/wander
/usr/libexec/xscreensaver/webcollage
/usr/libexec/xscreensaver/whirlwindwarp
/usr/libexec/xscreensaver/wormhole
/usr/libexec/xscreensaver/xanalogtv
/usr/libexec/xscreensaver/xflame
/usr/libexec/xscreensaver/xjack
/usr/libexec/xscreensaver/xlyap
/usr/libexec/xscreensaver/xmatrix
/usr/libexec/xscreensaver/xrayswarm
/usr/libexec/xscreensaver/xspirograph
/usr/libexec/xscreensaver/zoom

%files data
%defattr(-,root,root,-)
/usr/share/pam.d/xscreensaver
/usr/share/xscreensaver/config/README
/usr/share/xscreensaver/config/abstractile.xml
/usr/share/xscreensaver/config/anemone.xml
/usr/share/xscreensaver/config/anemotaxis.xml
/usr/share/xscreensaver/config/apollonian.xml
/usr/share/xscreensaver/config/apple2.xml
/usr/share/xscreensaver/config/attraction.xml
/usr/share/xscreensaver/config/barcode.xml
/usr/share/xscreensaver/config/binaryring.xml
/usr/share/xscreensaver/config/blaster.xml
/usr/share/xscreensaver/config/blitspin.xml
/usr/share/xscreensaver/config/bouboule.xml
/usr/share/xscreensaver/config/boxfit.xml
/usr/share/xscreensaver/config/braid.xml
/usr/share/xscreensaver/config/bsod.xml
/usr/share/xscreensaver/config/bumps.xml
/usr/share/xscreensaver/config/ccurve.xml
/usr/share/xscreensaver/config/celtic.xml
/usr/share/xscreensaver/config/cloudlife.xml
/usr/share/xscreensaver/config/compass.xml
/usr/share/xscreensaver/config/coral.xml
/usr/share/xscreensaver/config/crystal.xml
/usr/share/xscreensaver/config/cwaves.xml
/usr/share/xscreensaver/config/cynosure.xml
/usr/share/xscreensaver/config/decayscreen.xml
/usr/share/xscreensaver/config/deco.xml
/usr/share/xscreensaver/config/deluxe.xml
/usr/share/xscreensaver/config/demon.xml
/usr/share/xscreensaver/config/discrete.xml
/usr/share/xscreensaver/config/distort.xml
/usr/share/xscreensaver/config/drift.xml
/usr/share/xscreensaver/config/epicycle.xml
/usr/share/xscreensaver/config/eruption.xml
/usr/share/xscreensaver/config/euler2d.xml
/usr/share/xscreensaver/config/fadeplot.xml
/usr/share/xscreensaver/config/fiberlamp.xml
/usr/share/xscreensaver/config/fireworkx.xml
/usr/share/xscreensaver/config/flame.xml
/usr/share/xscreensaver/config/flow.xml
/usr/share/xscreensaver/config/fluidballs.xml
/usr/share/xscreensaver/config/fontglide.xml
/usr/share/xscreensaver/config/fuzzyflakes.xml
/usr/share/xscreensaver/config/galaxy.xml
/usr/share/xscreensaver/config/goop.xml
/usr/share/xscreensaver/config/grav.xml
/usr/share/xscreensaver/config/greynetic.xml
/usr/share/xscreensaver/config/halftone.xml
/usr/share/xscreensaver/config/halo.xml
/usr/share/xscreensaver/config/helix.xml
/usr/share/xscreensaver/config/hexadrop.xml
/usr/share/xscreensaver/config/hopalong.xml
/usr/share/xscreensaver/config/ifs.xml
/usr/share/xscreensaver/config/imsmap.xml
/usr/share/xscreensaver/config/interaggregate.xml
/usr/share/xscreensaver/config/interference.xml
/usr/share/xscreensaver/config/intermomentary.xml
/usr/share/xscreensaver/config/julia.xml
/usr/share/xscreensaver/config/kaleidescope.xml
/usr/share/xscreensaver/config/kumppa.xml
/usr/share/xscreensaver/config/lcdscrub.xml
/usr/share/xscreensaver/config/loop.xml
/usr/share/xscreensaver/config/m6502.xml
/usr/share/xscreensaver/config/maze.xml
/usr/share/xscreensaver/config/memscroller.xml
/usr/share/xscreensaver/config/metaballs.xml
/usr/share/xscreensaver/config/moire.xml
/usr/share/xscreensaver/config/moire2.xml
/usr/share/xscreensaver/config/mountain.xml
/usr/share/xscreensaver/config/munch.xml
/usr/share/xscreensaver/config/nerverot.xml
/usr/share/xscreensaver/config/noseguy.xml
/usr/share/xscreensaver/config/pacman.xml
/usr/share/xscreensaver/config/pedal.xml
/usr/share/xscreensaver/config/penetrate.xml
/usr/share/xscreensaver/config/penrose.xml
/usr/share/xscreensaver/config/petri.xml
/usr/share/xscreensaver/config/phosphor.xml
/usr/share/xscreensaver/config/piecewise.xml
/usr/share/xscreensaver/config/polyominoes.xml
/usr/share/xscreensaver/config/pong.xml
/usr/share/xscreensaver/config/popsquares.xml
/usr/share/xscreensaver/config/pyro.xml
/usr/share/xscreensaver/config/qix.xml
/usr/share/xscreensaver/config/rd-bomb.xml
/usr/share/xscreensaver/config/ripples.xml
/usr/share/xscreensaver/config/rocks.xml
/usr/share/xscreensaver/config/rorschach.xml
/usr/share/xscreensaver/config/rotzoomer.xml
/usr/share/xscreensaver/config/shadebobs.xml
/usr/share/xscreensaver/config/sierpinski.xml
/usr/share/xscreensaver/config/slidescreen.xml
/usr/share/xscreensaver/config/slip.xml
/usr/share/xscreensaver/config/speedmine.xml
/usr/share/xscreensaver/config/spotlight.xml
/usr/share/xscreensaver/config/squiral.xml
/usr/share/xscreensaver/config/starfish.xml
/usr/share/xscreensaver/config/strange.xml
/usr/share/xscreensaver/config/substrate.xml
/usr/share/xscreensaver/config/swirl.xml
/usr/share/xscreensaver/config/tessellimage.xml
/usr/share/xscreensaver/config/thornbird.xml
/usr/share/xscreensaver/config/triangle.xml
/usr/share/xscreensaver/config/truchet.xml
/usr/share/xscreensaver/config/twang.xml
/usr/share/xscreensaver/config/vermiculate.xml
/usr/share/xscreensaver/config/vidwhacker.xml
/usr/share/xscreensaver/config/wander.xml
/usr/share/xscreensaver/config/webcollage.xml
/usr/share/xscreensaver/config/whirlwindwarp.xml
/usr/share/xscreensaver/config/wormhole.xml
/usr/share/xscreensaver/config/xanalogtv.xml
/usr/share/xscreensaver/config/xflame.xml
/usr/share/xscreensaver/config/xjack.xml
/usr/share/xscreensaver/config/xlyap.xml
/usr/share/xscreensaver/config/xmatrix.xml
/usr/share/xscreensaver/config/xrayswarm.xml
/usr/share/xscreensaver/config/xspirograph.xml
/usr/share/xscreensaver/config/zoom.xml

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%doc /usr/share/man/man6/*

%files locales -f xscreensaver.lang 
%defattr(-,root,root,-)

